# Maven package Java project Web App to Linux on Azure
# Build your Java project
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '07d9db30-cf0e-4048-b6cd-cc5b1b2bb0cd'

  # Web app name
  webAppName: 'Spring-boot'

  # Environment name
  environmentName: 'Dev'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
      container: maven:3.8.1-openjdk-17-slim
      variables:
      - name: JAVA_HOME_11_X64
        value: /usr/local/openjdk-17

    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'complete/pom.xml'
        javaHomeSelection: 'path'
        jdkDirectory: '/usr/local/openjdk-17'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.?(war|jar)'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop